// SUMMONER - カードDB（通常カード105種＋召喚士25種）
// 120種.txt を基に調整。現行ルールではカード種類を問わず同名4枚まで。
const DB = {
  "陽炎のジン": { code:"BS01-001", t:"monster", color:"red", race:"妖精", c:1, a:1, h:1, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "ボウガンスタチュー": { code:"BS01-002", t:"monster", color:"red", race:"機械", c:1, a:2, h:1, txt:"攻撃するとき、自身の召喚士ゾーンから1枚選び墓地へ置く。", n:4, effectKey:"sacLandOnAttack" },
  "斥候ゴブリン": { code:"BS01-003", t:"monster", color:"red", race:"ゴブリン", c:2, a:1, h:1, txt:"【速攻】（このモンスターは登場したターンに攻撃できる）", n:4, effectKey:"haste", haste:true },
  "熱波のジン": { code:"BS01-004", t:"monster", color:"red", race:"妖精", c:2, a:3, h:1, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "アックス・ソルジャー": { code:"BS01-005", t:"monster", color:"red", race:"人間・戦士", c:3, a:3, h:3, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "ブレード・ソルジャー": { code:"BS01-006", t:"monster", color:"red", race:"人間・戦士", c:3, a:2, h:3, txt:"【速攻】（このモンスターは登場したターンに攻撃できる）", n:4, effectKey:"haste", haste:true },
  "サルファ・ゴーレム": { code:"BS01-007", t:"monster", color:"red", race:"ゴーレム", c:4, a:3, h:4, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "ガトリングスタチュー": { code:"BS01-008", t:"monster", color:"red", race:"機械", c:4, a:4, h:2, txt:"アンタップしているモンスターを攻撃できる。", n:4, effectKey:"vanilla" },
  "放電のジン": { code:"BS01-009", t:"monster", color:"red", race:"妖精", c:5, a:5, h:5, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "ランチャースタチュー": { code:"BS01-010", t:"monster", color:"red", race:"機械", c:5, a:4, h:3, txt:"アンタップしているモンスターを攻撃できる。", n:4, effectKey:"vanilla" },
  "マグマ・ゴーレム": { code:"BS01-011", t:"monster", color:"red", race:"ゴーレム", c:5, a:8, h:6, txt:"攻撃するとき、自身の召喚士ゾーンから1枚選び墓地へ置く。", n:4, effectKey:"sacLandOnAttack" },
  "ボルケーノ・ドラゴン": { code:"BS01-012", t:"monster", color:"red", race:"ドラゴン", c:6, a:6, h:6, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "竜皇アレキサンダー": { code:"BS01-013", t:"monster", color:"red", race:"ドラゴン", c:6, a:6, h:6, txt:"【速攻】（このモンスターは登場したターンに攻撃できる）。攻撃時、相手プレイヤーに3ダメージを与える。", n:4, effectKey:"hasteBurn3", haste:true },
  "バーンアウト・ドラゴン": { code:"BS01-014", t:"monster", color:"red", race:"ドラゴン", c:8, a:4, h:3, txt:"登場時、 相手の召喚士ゾーンのカード1枚を対象にとる。そのカードを持ち主の墓地へ置く。", n:4, effectKey:"destroyOppLand" },
  "フルバースト・ドラゴン": { code:"BS01-015", t:"monster", color:"red", race:"ドラゴン", c:8, a:5, h:2, txt:"登場時、相手モンスター全てに3ダメージを与える。", n:4, effectKey:"damageAll3" },
  "火山弾": { code:"BS01-016", t:"spell", color:"red", race:"火", c:4, a:0, h:0, txt:"相手モンスター全てに3ダメージを与える。", n:4, effectKey:"damageAll3" },
  "ファイヤーシュート": { code:"BS01-017", t:"spell", color:"red", race:"火", c:4, a:0, h:0, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） 相手の戦場のモンスター1体を対象にとる。そのモンスターに2ダメージを与える。", n:4, effectKey:"damageOpp2", timing:"instant" },
  "稲妻": { code:"BS01-018", t:"spell", color:"red", race:"雷", c:4, a:0, h:0, txt:"相手プレイヤーに4ダメージを与える。", n:4, effectKey:"face4" },
  "火山雷": { code:"BS01-019", t:"spell", color:"red", race:"火・雷", c:5, a:0, h:0, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） 以下の効果から1つ選ぶ。 ・相手プレイヤーに3ダメージを与える。 ・相手の戦場のモンスター1体を対象にとる。そのモンスターに3ダメージを与える。", n:4, effectKey:"chooseBurn3", timing:"instant" },
  "突撃命令": { code:"BS01-020", t:"spell", color:"red", race:"戦術", c:5, a:0, h:0, txt:"自分の戦場のモンスター全てはターン終了時までアンタップしているモンスターを攻撃できる。", n:4, effectKey:"attackUntappedEOT" },
  "焦土作戦": { code:"BS01-021", t:"spell", color:"red", race:"戦術", c:5, a:0, h:0, txt:"相手の召喚士ゾーンのカード1枚を対象にとる。そのカードを持ち主の墓地へ置く。", n:4, effectKey:"destroyOppLand" },
  "バイオ・シールダー": { code:"BS01-022", t:"monster", color:"blue", race:"ゲルノイド", c:1, a:1, h:2, txt:"攻撃できない。", n:4, effectKey:"cannotAttack" },
  "バイオ・シューター": { code:"BS01-023", t:"monster", color:"blue", race:"ゲルノイド", c:2, a:1, h:1, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "さざ波のマーメイド": { code:"BS01-024", t:"monster", color:"blue", race:"マーフォーク", c:3, a:2, h:2, txt:"登場時、山札から1枚引く。", n:4, effectKey:"draw1" },
  "スケーター・ペンギン": { code:"BS01-025", t:"monster", color:"blue", race:"ビースト", c:3, a:1, h:2, txt:"ブロックされない。", n:4, effectKey:"unblockable" },
  "バイオ・ファイター": { code:"BS01-026", t:"monster", color:"blue", race:"ゲルノイド", c:3, a:1, h:2, txt:"このモンスターが墓地へ送られるとき、代わりに手札に戻す。", n:4, effectKey:"returnOnDeath" },
  "エコー・ドルフィン": { code:"BS01-027", t:"monster", color:"blue", race:"ビースト", c:3, a:2, h:4, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "潮騒のマーメイド": { code:"BS01-028", t:"monster", color:"blue", race:"マーフォーク", c:4, a:4, h:3, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "ディープ・カルジャン": { code:"BS01-029", t:"monster", color:"blue", race:"ケートス", c:4, a:2, h:3, txt:"ブロックされない。", n:4, effectKey:"unblockable" },
  "クリアー・トゥース": { code:"BS01-030", t:"monster", color:"blue", race:"ビースト", c:5, a:5, h:6, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "海嘯のマーメイド": { code:"BS01-031", t:"monster", color:"blue", race:"マーフォーク", c:6, a:5, h:5, txt:"登場時、カードを2枚引く。", n:4, effectKey:"draw2" },
  "ディープ・エルブルス": { code:"BS01-032", t:"monster", color:"blue", race:"ケートス", c:7, a:4, h:4, txt:"ブロックされない。", n:4, effectKey:"unblockable" },
  "ディープ・マッキンリー": { code:"BS01-033", t:"monster", color:"blue", race:"ケートス", c:7, a:3, h:4, txt:"登場時、相手の場のモンスターをすべて手札に戻す。", n:4, effectKey:"bounceAllOpp" },
  "サイクロン": { code:"BS01-034", t:"spell", color:"blue", race:"風", c:2, a:0, h:0, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） 場のモンスター1体を対象にとる。そのモンスターを手札に戻す。", n:4, effectKey:"bounceAny", timing:"instant" },
  "水鏡": { code:"BS01-035", t:"spell", color:"blue", race:"水", c:3, a:0, h:0, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） 相手モンスターが攻撃したとき、そのモンスターを破壊する。", n:4, effectKey:"counterAttack", timing:"instant" },
  "離岸流": { code:"BS01-036", t:"spell", color:"blue", race:"水", c:4, a:0, h:0, txt:"HP3以下のモンスターを全て手札に戻す。", n:4, effectKey:"bounceHp3" },
  "大いなる知恵": { code:"BS01-037", t:"spell", color:"blue", race:"魔法", c:4, a:0, h:0, txt:"カードを3枚引く。", n:4, effectKey:"draw3" },
  "詠唱破棄": { code:"BS01-038", t:"spell", color:"blue", race:"魔法", c:4, a:0, h:0, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） 相手が召喚士以外のカードをプレイするとき、そのカードを無効化し墓地に置く。", n:4, effectKey:"counterPlay", timing:"instant" },
  "ゲル・プロテクション": { code:"BS01-039", t:"spell", color:"blue", race:"魔法", c:5, a:0, h:0, txt:"自分の戦場のモンスター全ては、ターン終了時までそのモンスターが墓地へ送られるとき、代わりに手札に戻す。", n:4, effectKey:"returnAllOnDeath" },
  "波乗り": { code:"BS01-040", t:"spell", color:"blue", race:"戦術", c:5, a:0, h:0, txt:"自分の戦場のモンスター全ては、ターン終了時までブロックされない。", n:4, effectKey:"teamUnblockable" },
  "洪水": { code:"BS01-041", t:"spell", color:"blue", race:"魔法", c:6, a:0, h:0, txt:"場のモンスターをすべて手札に戻す。", n:4, effectKey:"bounceAll" },
  "オムニ・マインド": { code:"BS01-042", t:"spell", color:"blue", race:"魔法", c:6, a:0, h:0, txt:"カードを5枚引く。その後手札を4枚選び山札の下に好きな順番で置く。", n:4, effectKey:"draw5Bottom4" },
  "森の妖精": { code:"BS01-043", t:"monster", color:"green", race:"妖精", c:1, a:0, h:1, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "英雄の角": { code:"BS01-044", t:"monster", color:"green", race:"ビースト", c:2, a:1, h:2, txt:"このモンスターが墓地へ送られるとき、代わりに裏向きで召喚士ゾーンに置く。", n:4, effectKey:"faceDownLandOnDeath" },
  "弓術エルフ": { code:"BS01-045", t:"monster", color:"green", race:"エルフ", c:2, a:2, h:1, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "仙道エルフ": { code:"BS01-046", t:"monster", color:"green", race:"エルフ", c:2, a:1, h:1, txt:"登場時、自分の手札を1枚、自分の召喚士ゾーンに裏向きで置く。", n:4, effectKey:"handToFaceDownLand" },
  "深緑のシャーマン": { code:"BS01-047", t:"monster", color:"green", race:"魔導士", c:3, a:1, h:2, txt:"登場時、自分の山札を見る。その中から召喚士カードを1つ選び、召喚士ゾーンに置く。その後山札をシャッフルする。", n:4, effectKey:"searchLand" },
  "槍術エルフ": { code:"BS01-048", t:"monster", color:"green", race:"エルフ", c:3, a:3, h:4, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "スラッシュ・マンティス": { code:"BS01-049", t:"monster", color:"green", race:"昆虫", c:4, a:3, h:2, txt:"このモンスターが墓地へ送られるとき、代わりに裏向きで召喚士ゾーンに置く。", n:4, effectKey:"faceDownLandOnDeath" },
  "剣術エルフ": { code:"BS01-050", t:"monster", color:"green", race:"昆虫", c:4, a:4, h:3, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "親分": { code:"BS01-051", t:"monster", color:"green", race:"ビースト", c:4, a:2, h:2, txt:"このモンスターが戦場にいる限り、味方全体のATKを＋1する。", n:4, effectKey:"auraAtk1" },
  "賢者の腕": { code:"BS01-052", t:"monster", color:"green", race:"ビースト", c:5, a:6, h:4, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "クラッシュ・ビートル": { code:"BS01-053", t:"monster", color:"green", race:"昆虫", c:5, a:5, h:4, txt:"このモンスターが相手モンスターをバトルで破壊したとき発動する。このモンスターをアンタップする。", n:4, effectKey:"untapOnKill" },
  "大樹のシャーマン": { code:"BS01-054", t:"monster", color:"green", race:"魔導士", c:5, a:4, h:4, txt:"登場時、自分の墓地のモンスター1体を対象にとる。そのモンスターを自分の召喚士ゾーンに裏向きで置く。", n:4, effectKey:"graveToFaceDownLand" },
  "迎撃トレント": { code:"BS01-055", t:"monster", color:"green", race:"妖精", c:5, a:4, h:4, txt:"このモンスターは相手プレイヤーを攻撃できない。", n:4, effectKey:"cannotAttackFace" },
  "バニッシュスパイダー": { code:"BS01-056", t:"monster", color:"green", race:"昆虫", c:6, a:3, h:4, txt:"登場時、相手の戦場のモンスター1体を対象にとる。そのモンスターをもともとの持ち主の召喚士ゾーンに裏向きで置く。", n:4, effectKey:"oppToFaceDownLand" },
  "不死の巨像": { code:"BS01-057", t:"monster", color:"green", race:"妖精", c:6, a:7, h:6, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "生命変換": { code:"BS01-058", t:"spell", color:"green", race:"霊術", c:2, a:0, h:0, txt:"自分の戦場のモンスター1体を対象にとる。そのモンスターを自分の召喚士ゾーンに裏向きで置く。", n:4, effectKey:"ownToFaceDownLand" },
  "叫声": { code:"BS01-059", t:"spell", color:"green", race:"戦術", c:3, a:0, h:0, txt:"自分の山札を見る。その中からモンスターカードを1つ選び、手札に加える。その後山札をシャッフルする。", n:4, effectKey:"searchMonster" },
  "本能活性": { code:"BS01-060", t:"spell", color:"green", race:"パワー", c:4, a:0, h:0, txt:"自分の戦場のモンスター全ては、ターン終了時までATKを＋3する。", n:4, effectKey:"teamAtk3" },
  "大地へと還れ": { code:"BS01-061", t:"spell", color:"green", race:"霊術", c:4, a:0, h:0, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） 相手の戦場のモンスター1体を対象にとる。そのモンスターを相手の召喚士ゾーンに裏向きで置く。", n:4, effectKey:"oppToFaceDownLand", timing:"instant" },
  "フォレスト・チャージ": { code:"BS01-062", t:"spell", color:"green", race:"霊術", c:5, a:0, h:0, txt:"自分の山札を見る。その中から召喚士カードを2つ選び、召喚士ゾーンに置く。その後山札をシャッフルする。", n:4, effectKey:"search2Land" },
  "魂死なず": { code:"BS01-063", t:"spell", color:"green", race:"霊術", c:5, a:0, h:0, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） ターン終了時まで、自分のモンスターが墓地へ送られるとき、代わりに裏向きで召喚士ゾーンに置く。", n:4, effectKey:"soulNever", timing:"instant" },
  "セイント・コーム": { code:"BS01-064", t:"monster", color:"yellow", race:"機械", c:1, a:0, h:3, txt:"攻撃できない。", n:4, effectKey:"cannotAttack" },
  "パラディン": { code:"BS01-065", t:"monster", color:"yellow", race:"人間・戦士", c:2, a:1, h:3, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "メイガス": { code:"BS01-066", t:"monster", color:"yellow", race:"人間・戦士", c:3, a:1, h:3, txt:"このモンスターがブロックするとき、このモンスターのHPをターン終了時まで+2する。", n:4, effectKey:"blockHpPlus2" },
  "セイント・クロー": { code:"BS01-067", t:"monster", color:"yellow", race:"機械", c:3, a:2, h:3, txt:"自分のターン終了時、このモンスターをアンタップする。", n:4, effectKey:"untapSelfEnd" },
  "インクイジター": { code:"BS01-068", t:"monster", color:"yellow", race:"人間・戦士", c:4, a:4, h:4, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "セイント・ビーク": { code:"BS01-069", t:"monster", color:"yellow", race:"機械", c:4, a:3, h:2, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） なし（バニラ）", n:4, effectKey:"vanilla", timing:"instant" },
  "モンク": { code:"BS01-070", t:"monster", color:"yellow", race:"人間・戦士", c:4, a:3, h:3, txt:"自分のターン終了時、このモンスターをアンタップする。", n:4, effectKey:"untapSelfEnd" },
  "セイント・メイン": { code:"BS01-071", t:"monster", color:"yellow", race:"機械", c:5, a:4, h:6, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "アークエンジェル": { code:"BS01-072", t:"monster", color:"yellow", race:"天使", c:5, a:2, h:3, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） 登場時、相手の戦場のモンスター1体を対象にとる。そのモンスターをタップする。", n:4, effectKey:"tapOppOnSummon", timing:"instant" },
  "天より来たるエクスシア": { code:"BS01-073", t:"monster", color:"yellow", race:"天使", c:6, a:3, h:3, txt:"登場時、自分の山札を見る。その中からスペルカードを1つ選び、手札に加える。その後山札をシャッフルする。", n:4, effectKey:"searchSpell" },
  "天より来たるデュナミス": { code:"BS01-074", t:"monster", color:"yellow", race:"天使", c:6, a:5, h:4, txt:"自分のターン終了時、このモンスターをアンタップする。", n:4, effectKey:"untapSelfEnd" },
  "天より来たるプリンシパリティ": { code:"BS01-075", t:"monster", color:"yellow", race:"天使", c:7, a:4, h:6, txt:"登場時、相手のモンスターを全てタップする。", n:4, effectKey:"tapAllOpp" },
  "プロテクション": { code:"BS01-076", t:"spell", color:"yellow", race:"回復・水", c:2, a:0, h:0, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） 次に自分が受けるダメージを3軽減する。", n:4, effectKey:"prevent3", timing:"instant" },
  "聖水": { code:"BS01-077", t:"spell", color:"yellow", race:"回復・水", c:2, a:0, h:0, txt:"自分のLPを2回復する。", n:4, effectKey:"heal2" },
  "加護": { code:"BS01-078", t:"spell", color:"yellow", race:"光", c:3, a:0, h:0, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） ターン終了時まで自分のモンスターは1度だけ破壊されない。", n:4, effectKey:"indestructibleOnce", timing:"instant" },
  "ジャッジ・アロー": { code:"BS01-079", t:"spell", color:"yellow", race:"光", c:3, a:0, h:0, txt:"相手のモンスターを2体まで対象に取る。対象のモンスターをタップする。", n:4, effectKey:"tapUpTo2" },
  "天の名の下に": { code:"BS01-080", t:"spell", color:"yellow", race:"戦術・光", c:3, a:0, h:0, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） 手札からコスト3以下のモンスターを1体、コストを支払わず場に出す。", n:4, effectKey:"freeSummon3", timing:"instant" },
  "聖泉": { code:"BS01-081", t:"spell", color:"yellow", race:"水", c:4, a:0, h:0, txt:"自分のLPを4回復する。", n:4, effectKey:"heal4" },
  "閃光": { code:"BS01-082", t:"spell", color:"yellow", race:"光", c:4, a:0, h:0, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） 相手のモンスターを全てタップする。", n:4, effectKey:"tapAllOpp", timing:"instant" },
  "防壁": { code:"BS01-083", t:"spell", color:"yellow", race:"戦術・光", c:5, a:0, h:0, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） 自分の場のモンスターすべてのHPをターン終了時まで＋3する", n:4, effectKey:"hpPlus3Team", timing:"instant" },
  "裁き": { code:"BS01-084", t:"spell", color:"yellow", race:"光", c:6, a:0, h:0, txt:"全てのモンスターを破壊する。", n:4, effectKey:"destroyAll" },
  "憤怒するゾンビ": { code:"BS01-085", t:"monster", color:"black", race:"ゴースト", c:1, a:3, h:1, txt:"登場時、自分のモンスターを1枚を墓地に送る。", n:4, effectKey:"sacOwnOnSummon" },
  "ボーン・ソルジャー": { code:"BS01-086", t:"monster", color:"black", race:"ゴースト・戦士", c:2, a:2, h:2, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "蝋燭印のサキュバス": { code:"BS01-087", t:"monster", color:"black", race:"魔人", c:2, a:1, h:2, txt:"登場時、相手の戦場のモンスター1体を対象にとる。対象のモンスターはターン終了時までHPを-1する。", n:4, effectKey:"hpMinus1EOT" },
  "駆け巡るゾンビ": { code:"BS01-088", t:"monster", color:"black", race:"ゴースト", c:3, a:2, h:4, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "杯印のサキュバス": { code:"BS01-089", t:"monster", color:"black", race:"魔人", c:4, a:5, h:4, txt:"登場時、自分のモンスターを1枚を墓地に送る。", n:4, effectKey:"sacOwnOnSummon" },
  "新芽印のサキュバス": { code:"BS01-090", t:"monster", color:"black", race:"魔人", c:5, a:2, h:3, txt:"登場時、相手の手札を1枚ランダムに墓地へ送る。", n:4, effectKey:"discardRandomOpp" },
  "ボーン・アサルト": { code:"BS01-091", t:"monster", color:"black", race:"ゴースト", c:5, a:2, h:3, txt:"【接死】（このモンスターがダメージを受けたモンスターを破壊する）", n:4, effectKey:"deathtouch" },
  "恐れの牙アロケル": { code:"BS01-092", t:"monster", color:"black", race:"悪魔", c:6, a:6, h:6, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "三叉の魔将アガレス": { code:"BS01-093", t:"monster", color:"black", race:"悪魔", c:6, a:4, h:6, txt:"登場時、相手の戦場のモンスター1体を対象にとる。そのモンスターを破壊する。", n:4, effectKey:"destroyOppMonster" },
  "円匙印のサキュバス": { code:"BS01-094", t:"monster", color:"black", race:"魔人", c:7, a:3, h:3, txt:"自分の墓地のモンスターを2体まで対象にとる。そのモンスターを手札に加える。", n:4, effectKey:"recoverUpTo2" },
  "禁忌の蹄ガミジン": { code:"BS01-095", t:"monster", color:"black", race:"悪魔", c:7, a:7, h:6, txt:"なし（バニラ）", n:4, effectKey:"vanilla" },
  "瘴気の乙女ネヴァン": { code:"BS01-096", t:"monster", color:"black", race:"魔導士", c:7, a:4, h:6, txt:"登場時、相手の戦場のモンスター全ては、ターン終了時までHPを-3する。", n:4, effectKey:"hpMinus3AllEOT" },
  "落丁": { code:"BS01-097", t:"spell", color:"black", race:"戦術", c:2, a:0, h:0, txt:"相手の手札を1枚ランダムに墓地へ送る。", n:4, effectKey:"discardRandomOpp" },
  "墓荒らし": { code:"BS01-098", t:"spell", color:"black", race:"戦術", c:2, a:0, h:0, txt:"自分の墓地のモンスターを1体対象にとる。そのモンスターを手札に加える。", n:4, effectKey:"recoverOne" },
  "毒針": { code:"BS01-099", t:"spell", color:"black", race:"暗器", c:3, a:0, h:0, txt:"相手のアンタップしているモンスター1体を対象にとる。そのモンスターを破壊する。", n:4, effectKey:"destroyUntappedOpp" },
  "死なばもろとも": { code:"BS01-100", t:"spell", color:"black", race:"戦術", c:3, a:0, h:0, txt:"自分と相手の戦場のモンスターそれぞれ1体を対象にとる。そのモンスターを破壊する。", n:4, effectKey:"destroyOneEach" },
  "キリング・フィールド": { code:"BS01-101", t:"spell", color:"black", race:"戦術", c:3, a:0, h:0, txt:"自分の場のモンスターすべてに、ターン終了時まで「接死」を与える。", n:4, effectKey:"teamDeathtouch" },
  "ソウル・ドレイン": { code:"BS01-102", t:"spell", color:"black", race:"黒魔術", c:4, a:0, h:0, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） 自分のモンスターを好きな枚数対象に発動できる。そのモンスターを破壊し、その枚数1枚につきライフを2回復する。", n:4, effectKey:"soulDrain", timing:"instant" },
  "魔神拳": { code:"BS01-103", t:"spell", color:"black", race:"黒魔術", c:4, a:0, h:0, txt:"【高速詠唱】（このカードはプレイ可能なら、いつでも発動できる） 相手の戦場のモンスター1体を対象にとる。そのモンスターを破壊する。", n:4, effectKey:"destroyOppMonster", timing:"instant" },
  "わが命を懸けて": { code:"BS01-104", t:"spell", color:"black", race:"黒魔術", c:4, a:0, h:0, txt:"自分のLPから3支払う。ターン終了時まで召喚士ゾーンに無色の陣を6追加する。", n:4, effectKey:"sixColorless", lpCost:3 },
  "瘴気の風": { code:"BS01-105", t:"spell", color:"black", race:"黒魔術", c:5, a:0, h:0, txt:"相手の戦場のモンスター全ては、ターン終了時までHPを-2する。", n:4, effectKey:"hpMinus2AllEOT" },

  // --- 召喚士（各色5種 / 計25種） ---
  "カイエン": { code:"BS01-106", t:"summoner", color:"red", race:"召喚士", c:0, a:0, h:0, txt:"タップ：赤の陣＋1　タップ＋◎1：相手のプレイヤーにダメージ2", n:4, effectKey:"mana", summonerAbilityKey:"face2", summonerAbilityCost:1 },
  "ジュニパー": { code:"BS01-107", t:"summoner", color:"red", race:"召喚士", c:0, a:0, h:0, txt:"タップ：赤の陣＋1　タップ：このターン召喚された自分のモンスター1体を対象にとる。そのモンスターはターン終了時まで【速攻】を得る", n:4, effectKey:"mana", summonerAbilityKey:"grantHaste", summonerAbilityCost:0 },
  "アムチュール": { code:"BS01-108", t:"summoner", color:"red", race:"召喚士", c:0, a:0, h:0, txt:"タップ：赤の陣＋1　タップ＋◎1：相手モンスターを破壊したとき相手のモンスター1体を対象に発動できる。そのモンスターにダメージ2", n:4, effectKey:"mana", summonerAbilityKey:"destroyTriggerBurn2", summonerAbilityCost:1, summonerTrigger:"destroyOpp" },
  "フェヌグリーク": { code:"BS01-109", t:"summoner", color:"red", race:"召喚士", c:0, a:0, h:0, txt:"タップ：赤の陣＋1　タップ＋◎2：自分ターン終了時に発動できる。このターンの攻撃回数が2回以上なら1枚引く", n:4, effectKey:"mana", summonerAbilityKey:"endDrawIf2Attacks", summonerAbilityCost:2, summonerTrigger:"turnEnd" },
  "フェンネル": { code:"BS01-110", t:"summoner", color:"red", race:"召喚士", c:0, a:0, h:0, txt:"タップ：赤の陣＋1　タップ：自分が種族にゴーレムを含むモンスターを召喚したとき発動できる。1枚引く", n:4, effectKey:"mana", summonerAbilityKey:"tribeSummonDraw", summonerAbilityCost:0, summonerTrigger:"summonRace", summonerTriggerRace:"ゴーレム" },

  "ルフナ": { code:"BS01-111", t:"summoner", color:"blue", race:"召喚士", c:0, a:0, h:0, txt:"タップ：青の陣＋1　タップ：山札の上から3枚見る。それらを好きな順番で山札の上に置く。", n:4, effectKey:"mana", summonerAbilityKey:"reorderTop3", summonerAbilityCost:0 },
  "グレイ": { code:"BS01-112", t:"summoner", color:"blue", race:"召喚士", c:0, a:0, h:0, txt:"タップ：青の陣＋1　タップ：相手モンスター1体を対象とする。ターン終了時までそのモンスターのATK-1。", n:4, effectKey:"mana", summonerAbilityKey:"oppAtkMinus1", summonerAbilityCost:0 },
  "アッサム": { code:"BS01-113", t:"summoner", color:"blue", race:"召喚士", c:0, a:0, h:0, txt:"タップ：青の陣＋1　タップ＋◎1：相手のアンタップ状態のモンスター1体を対象とする。そのモンスターをタップする。", n:4, effectKey:"mana", summonerAbilityKey:"tapOppUntapped", summonerAbilityCost:1 },
  "セイロン": { code:"BS01-114", t:"summoner", color:"blue", race:"召喚士", c:0, a:0, h:0, txt:"タップ：青の陣＋1　タップ＋◎1：自分のモンスター1体を対象にとる。そのモンスターはターン終了時までブロックされない", n:4, effectKey:"mana", summonerAbilityKey:"grantUnblockable", summonerAbilityCost:1 },
  "ダージリン": { code:"BS01-115", t:"summoner", color:"blue", race:"召喚士", c:0, a:0, h:0, txt:"タップ：青の陣＋1　タップ：自分が種族にケートスを含むモンスターを召喚したとき発動できる。1枚引く", n:4, effectKey:"mana", summonerAbilityKey:"tribeSummonDraw", summonerAbilityCost:0, summonerTrigger:"summonRace", summonerTriggerRace:"ケートス" },

  "オニキス": { code:"BS01-116", t:"summoner", color:"green", race:"召喚士", c:0, a:0, h:0, txt:"タップ：緑の陣＋1　タップ：自分のモンスター1体を対象とする。ターン終了時までそのモンスターのATK+1する", n:4, effectKey:"mana", summonerAbilityKey:"ownAtkPlus1", summonerAbilityCost:0 },
  "ジャスパー": { code:"BS01-117", t:"summoner", color:"green", race:"召喚士", c:0, a:0, h:0, txt:"タップ：緑の陣＋1　タップ：自分のデッキの上から1枚を表向きにする。それがモンスターなら手札に加える。モンスター以外なら山札の下に置く。", n:4, effectKey:"mana", summonerAbilityKey:"revealTopMonster", summonerAbilityCost:0 },
  "ベリル": { code:"BS01-118", t:"summoner", color:"green", race:"召喚士", c:0, a:0, h:0, txt:"タップ：緑の陣＋1　タップ：自分の召喚士1枚を対象にとる。その召喚士をアンタップする。", n:4, effectKey:"mana", summonerAbilityKey:"untapOwnSummoner", summonerAbilityCost:0 },
  "ジルコニア": { code:"BS01-119", t:"summoner", color:"green", race:"召喚士", c:0, a:0, h:0, txt:"タップ：緑の陣＋1　タップ：自分のモンスター1体を対象にとる。そのモンスターをタップする。次のターン終了時まで相手モンスターが攻撃するとき可能ならそのモンスターを攻撃する。", n:4, effectKey:"mana", summonerAbilityKey:"forceAttackTarget", summonerAbilityCost:0 },
  "ジェイド": { code:"BS01-120", t:"summoner", color:"green", race:"召喚士", c:0, a:0, h:0, txt:"タップ：緑の陣＋1　タップ：自分が種族にビーストを含むモンスターを召喚したとき発動できる。1枚引く", n:4, effectKey:"mana", summonerAbilityKey:"tribeSummonDraw", summonerAbilityCost:0, summonerTrigger:"summonRace", summonerTriggerRace:"ビースト" },

  "サミュエル": { code:"BS01-121", t:"summoner", color:"yellow", race:"召喚士", c:0, a:0, h:0, txt:"タップ：黄の陣＋1　タップ：自分のLPを1回復する。", n:4, effectKey:"mana", summonerAbilityKey:"heal1", summonerAbilityCost:0 },
  "ダニエル": { code:"BS01-122", t:"summoner", color:"yellow", race:"召喚士", c:0, a:0, h:0, txt:"タップ：黄の陣＋1　タップ：自分のモンスター1体を対象にとる。次のターン終了時までそのモンスターのHPを+1する", n:4, effectKey:"mana", summonerAbilityKey:"hpPlus1NextEnd", summonerAbilityCost:0 },
  "エリヤ": { code:"BS01-123", t:"summoner", color:"yellow", race:"召喚士", c:0, a:0, h:0, txt:"タップ：黄の陣＋1　タップ＋◎2：自分のターン終了時、自分のモンスターを全てアンタップする。", n:4, effectKey:"mana", summonerAbilityKey:"endUntapAll", summonerAbilityCost:2, summonerTrigger:"turnEnd" },
  "ヨナ": { code:"BS01-124", t:"summoner", color:"yellow", race:"召喚士", c:0, a:0, h:0, txt:"タップ：黄の陣＋1　タップ：自分ターン終了時、自分の召喚士が3枚以上あり召喚士以外のカードをプレイしていないなら1枚引く。", n:4, effectKey:"mana", summonerAbilityKey:"endDrawSummonerOnly", summonerAbilityCost:0, summonerTrigger:"turnEnd" },
  "ミカ": { code:"BS01-125", t:"summoner", color:"yellow", race:"召喚士", c:0, a:0, h:0, txt:"タップ：黄の陣＋1　タップ：自分が種族に人間を含むモンスターを召喚したとき発動できる。1枚引く", n:4, effectKey:"mana", summonerAbilityKey:"tribeSummonDraw", summonerAbilityCost:0, summonerTrigger:"summonRace", summonerTriggerRace:"人間" },

  "ダイキリ": { code:"BS01-126", t:"summoner", color:"black", race:"召喚士", c:0, a:0, h:0, txt:"タップ：黒の陣＋1　タップ：相手のモンスター1体を対象にとる。次のターン終了時までそのモンスターのHPを-1する", n:4, effectKey:"mana", summonerAbilityKey:"hpMinus1NextEnd", summonerAbilityCost:0 },
  "ギムレット": { code:"BS01-127", t:"summoner", color:"black", race:"召喚士", c:0, a:0, h:0, txt:"タップ：黒の陣＋1　タップ：自分のモンスター1体を対象にとる。そのモンスターはターン終了時まで【接死】を得る", n:4, effectKey:"mana", summonerAbilityKey:"grantDeathtouch", summonerAbilityCost:0 },
  "ネグローニ": { code:"BS01-128", t:"summoner", color:"black", race:"召喚士", c:0, a:0, h:0, txt:"タップ：黒の陣＋1　タップ：1枚引く。その後自分にダメージ2", n:4, effectKey:"mana", summonerAbilityKey:"draw1SelfDamage2", summonerAbilityCost:0 },
  "ヴューカレ": { code:"BS01-129", t:"summoner", color:"black", race:"召喚士", c:0, a:0, h:0, txt:"タップ：黒の陣＋1　タップ＋◎1：自分の山札の上から1枚を墓地へ送る。", n:4, effectKey:"mana", summonerAbilityKey:"millTop1", summonerAbilityCost:1 },
  "スプモーニ": { code:"BS01-130", t:"summoner", color:"black", race:"召喚士", c:0, a:0, h:0, txt:"タップ：黒の陣＋1　タップ：自分が種族にゴーストを含むモンスターを召喚したとき発動できる。1枚引く", n:4, effectKey:"mana", summonerAbilityKey:"tribeSummonDraw", summonerAbilityCost:0, summonerTrigger:"summonRace", summonerTriggerRace:"ゴースト" }
};
const CARD_ORDER = Object.keys(DB);
